# Generated by Django 4.2.5 on 2023-09-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='top_score',
            new_name='top_scorer',
        ),
    ]
